version: '3.9'

services:
  mrl_aca:
    build:
      context: .
      args:
        - USERNAME=user
        - USER_UID=1000
        - USER_GID=1000
    init: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    runtime: nvidia
    entrypoint:
      - /tmp/runfirst.sh
    ports:
      - '22222:22'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
      - '..:/workspace:rw'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
